# Generated by Django 4.2 on 2024-11-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="duration_hours",
            field=models.IntegerField(default=1, verbose_name="Продолжительность брони в часах"),
        ),
    ]
